// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/osa-hero-variants/ConversationalHero.tsx": () => import("../components/mockups/osa-hero-variants/ConversationalHero.tsx"),
  "./components/mockups/osa-hero-variants/IntentRouter.tsx": () => import("../components/mockups/osa-hero-variants/IntentRouter.tsx"),
  "./components/mockups/osa-hero-variants/TransactionDashboard.tsx": () => import("../components/mockups/osa-hero-variants/TransactionDashboard.tsx")
};
